### ISSUE TITLE
Add Python 3.10 support

### ISSUE THREAD

**Issue by pierre-muller** [jsirois/conscript#1]
Hello,
It would be nice to have support for Python 3.10 in this package. Thanks.

**Comment by jsirois** [comment]
Python 3.10 & 3.11 support is tested and available in conscript 0.1.4: https://pypi.org/project/conscript/0.1.4/

Thanks again @pierre-muller for pushing this forward.

**Comment by pierre-muller** [comment]
hello John, tested conscript 0.1.4 on python 3.10, it works great. Thanks a lot for your quick action!
